---
title: "05 Performance Measures"
author: "Prajwal Kumar,Koretagere Vijay Kumar"
date: "2023-05-15"

---
# Task

Apply all the steps you have learned in this session on the dataset from challenge of the last session (Product Backorders):

* Leaderboard visualization
* Tune a model with grid search
* Visualize the trade of between the precision and the recall and the optimal threshold
* ROC Plot
* Precision vs Recall Plot
* Gain Plot
* Lift Plot
* Dashboard with cowplot
---

```{r}
library(tidymodels)
library(magrittr)
library(dplyr)
library(sjmisc)
library(magrittr)
library(haven)
library(sjlabelled)
library(rsample)
library(recipes)
library(rstanarm)
library(broom.mixed)
library(h2o)
product_backorders_tbl <- read.csv("../../Back_order.csv")
product_backorders_tbl %>% glimpse()
```

```{r}
data_split <- initial_split(product_backorders_tbl, prop = 3/4)
# Assign training and test data
train_data <- training(data_split)
test_data  <- testing(data_split)
# Specifying of the response and the predictor variables
factor_names <- c("went_on_backorder")
product_rec <- 
  recipe(went_on_backorder ~ ., data = train_data) %>%  
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_mutate_at(factor_names, fn = as.factor) %>%
  prep()
d <- summary(product_rec)
train_tbl <- bake(product_rec, new_data = train_data)
test_tbl  <- bake(product_rec, new_data = test_data)
```

```{r}
h2o.init()
# Splitting the data for validation df
split_h2o <- h2o.splitFrame(as.h2o(train_tbl), ratios = c(0.75), seed = 1234)
train_h2o <- split_h2o[[1]]
valid_h2o <- split_h2o[[2]]
test_h2o  <- as.h2o(test_tbl)
# Predictors
y <- "went_on_backorder"
x <- setdiff(names(train_h2o), y)
```


```{r}
# AutoML Model
h2o.init()
h2o_models_automl <- h2o.automl(
  x = x,
  y = y,
  training_frame    = train_h2o,
  validation_frame  = valid_h2o,
  leaderboard_frame = test_h2o,
  max_runtime_secs  = 120,
  nfolds            = 5 
)
typeof(h2o_models_automl)
slotNames(h2o_models_automl)
h2o_models_automl@leaderboard 
#h2o_models_automl@leader
```


```{r}
h2o.init()
#h2o.getModel("StackedEnsemble_AllModels_3_AutoML_2_20230517_140427") %>% 
#h2o.saveModel(path = "h20models/")
h2o.loadModel("../../content/01_journal/h20models/StackedEnsemble_AllModels_3_AutoML_2_20230517_140427")
 extract_h2o_model_name_by_position <- function(h2o_leaderboard, n = 1, verbose = T) {
   
   model_name <- h2o_leaderboard %>%
     as_tibble() %>%
     slice(n) %>%
     pull(model_id)
   
   if (verbose) message(model_name)
   
   return(model_name)
   
 }
```


```{r}
#h2o_models_automl@leaderboard %>% 
#extract_h2o_model_name_by_position(6) %>% 
#h2o.getModel() %>% 
#h2o.saveModel(path = "h20_models/")
stacked_ensemble_h2o <- h2o.loadModel("../../content/01_journal/h20models/StackedEnsemble_AllModels_3_AutoML_2_20230517_140427")
stacked_ensemble_h2o
predictions <- h2o.predict(stacked_ensemble_h2o, newdata = as.h2o(test_tbl))
typeof(predictions)
predictions_tbl <- predictions %>% as_tibble()
predictions_tbl
```